# https://leetcode.com/problems/customer-order-frequency/description/


# Write your MySQL query statement below

SELECT
    C.CUSTOMER_ID, C.NAME
FROM
    CUSTOMERS C LEFT JOIN ORDERS O USING(CUSTOMER_ID) LEFT JOIN PRODUCT P USING(PRODUCT_ID)
GROUP BY C.CUSTOMER_ID
HAVING SUM(IF(ORDER_DATE LIKE '2020-06%', QUANTITY*PRICE,0)) >=100
AND SUM(IF(ORDER_DATE LIKE '2020-07%', QUANTITY*PRICE,0)) >=100
